name: Java CI with Gradle

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew build
      - uses: actions/upload-artifact@v3
        with:
          name: jar
          path: build/libs/ExampleMod-*-SNAPSHOT.jar